/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.Dtos.UserDto;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author phoen
 */
public class WorkstationView extends javax.swing.JFrame {

    private UserDto user;

    /**
     * Creates new form WorkstationView
     */
    public WorkstationView(UserDto user) throws PropertyVetoException {
        this.user = user;
        if (user == null || !user.isAuth()) {
            // Exibe uma mensagem de erro
            JOptionPane.showMessageDialog(null, "Usuário não autenticado! A aplicação será encerrada.", "Erro de Autenticação", JOptionPane.ERROR_MESSAGE);
            System.exit(0); // Encerra a aplicação
        }

        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitItem = new javax.swing.JMenuItem();
        menuUsers = new javax.swing.JMenu();
        addUser = new javax.swing.JMenuItem();
        managerUsers = new javax.swing.JMenuItem();
        menuEmployees = new javax.swing.JMenu();
        addEmployee = new javax.swing.JMenuItem();
        managerEmployees = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText(user.getName());
        jMenu1.add(jSeparator1);

        exitItem.setText("Sair");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitItem);

        jMenuBar1.add(jMenu1);

        menuUsers.setText("Usuários");

        addUser.setText("Cadastrar");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });
        menuUsers.add(addUser);

        managerUsers.setText("Gerenciar");
        managerUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerUsersActionPerformed(evt);
            }
        });
        menuUsers.add(managerUsers);

        jMenuBar1.add(menuUsers);

        menuEmployees.setText("Funcionários");

        addEmployee.setText("Cadastrar");
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });
        menuEmployees.add(addEmployee);

        managerEmployees.setText("Gerenciar");
        managerEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerEmployeesActionPerformed(evt);
            }
        });
        menuEmployees.add(managerEmployees);

        jMenuBar1.add(menuEmployees);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitItemActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            UserFormView userFormView = new UserFormView();
            userFormView.setTitle("Novo usuário");
            userFormView.setVisible(true);
        });
    }//GEN-LAST:event_addUserActionPerformed

    private void managerUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerUsersActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            UserTableView userTableView = new UserTableView();
            userTableView.setVisible(true);
        });
    }//GEN-LAST:event_managerUsersActionPerformed

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            EmployeeFormView employeeFormView = new EmployeeFormView(user.getId());
            employeeFormView.setTitle("Novo funcionario");
            employeeFormView.setVisible(true);
        });
    }//GEN-LAST:event_addEmployeeActionPerformed

    private void managerEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerEmployeesActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            EmployeeTableView employeeTableView = new EmployeeTableView(user.getId());
            employeeTableView.setVisible(true);
        });
    }//GEN-LAST:event_managerEmployeesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addEmployee;
    private javax.swing.JMenuItem addUser;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem managerEmployees;
    private javax.swing.JMenuItem managerUsers;
    private javax.swing.JMenu menuEmployees;
    private javax.swing.JMenu menuUsers;
    // End of variables declaration//GEN-END:variables
}
